plugins {
    id 'com.android.application'
}

android {
    namespace 'aiv.ashivered.safebrowser'
    compileSdk 35

    defaultConfig {
        applicationId 'aiv.ashivered.safebrowser'
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName '5.0'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    // ABI Splits (smaller APK size)
    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            universalApk true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildToolsVersion = "34.0.0"
    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/NOTICE']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.preference:preference:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // GeckoView (not geckoview-fat for smaller size)
    implementation 'org.mozilla.geckoview:geckoview:136.0.20250227124745'
}
